fix: arrange dependent expansions accordingly
olets/zsh-abbr pull request #141
Opened 2024-06-24 09:37 UTC by henrebotha

Commit [a97788d](https://github.com/olets/zsh-abbr/commit/a97788d03ed7a0a8342b4e31b6a08fb29e15ff3a) introduces a simple error by moving the definition of `ABBR_LINE_CURSOR_MARKER` below where it's read (by the `ABBR_EXPANSION_CURSOR_MARKER` definition).

2024-06-24 09:38 UTC, henrebotha commented
Not sure which branch to target — I assume either `next` or `v6`, but let me know if I should change it.

2024-06-24 09:39 UTC, henrebotha commented
Also, wasn't sure how to write a test for this. All tests pass before and after this change.

2024-06-25 00:00 UTC, olets commented
Good catch, thanks! Fix looks right.

> Not sure which branch to target

`main` please. If into `next`, merging into `main` will be blocked by waiting for me to cut the next release (low bar, but still… don't want to be the blocker). If into `v6`, merging will into `main` will be blocked by releasing v6 (higher bar, could be a long wait).

> a test for this

Off the top of my head, untested, it will be:

- In `tests/index`
  - where user configs are saved, save the user's `ABBR_LINE_CURSOR_MARKER` and `ABBR_EXPANSION_CURSOR_MARKER`
  -  where test context is set, unset `ABBR_EXPANSION_CURSOR_MARKER`, and set `ABBR_LINE_CURSOR_MARKER` to something not the default (maybe `%%`?)
  - where user config is restored, restore the user's `ABBR_LINE_CURSOR_MARKER` and `ABBR_EXPANSION_CURSOR_MARKER`
- Add `tests/abbr-config` (breaks the pattern of the files being named for subcommands, but oh well), which has one test for whether `ABBR_LINE_CURSOR_MARKER` and `ABBR_EXPANSION_CURSOR_MARKER` are the same

If you're up for adding that, that'd be great!

2024-06-25 09:23 UTC, henrebotha commented
The test to catch the bug needs to actually unset both parameters, because the error only occurs when `ABBR_EXPANSION_CURSOR_MARKER` tries to default to the value of `ABBR_LINE_CURSOR_MARKER` before the latter is set. So I just added a test case for that instead.

2024-06-25 20:45 UTC, olets requested changes
excellent! one tiny request

2024-06-25 20:45 UTC, olets commented on tests/index.ztr.zsh
> +	abbr_line_cursor_marker_saved=$ABBR_LINE_CURSOR_MARKER
let's declare these as local, after line 23 (it's alphabetical)

2024-06-25 21:20 UTC, olets commented
Oh hm I just tried the new `./tests` in the `main` branch, and the new test passes when it should fail.

```
% git checkout main
% git checkout <this PR's branch> -- tests
% . ./tests/index.ztr.zsh config
PASS …
```

I haven't investigated.

2024-06-26 09:20 UTC, henrebotha commented
Haha, this is silly.

The commit that introduces the error is a97788d, which is not yet merged into `main`. So basing my fix on `main` is a little senseless; looking at the diff here, the actual change I made is not changing the ordering of the two relevant parameters, just shifting them down in the file. It's only in a97788d that the two parameters' order is reversed, introducing the error.

So base on `next` then?

2024-06-26 22:26 UTC, olets commented
Oh! Ha. Yes base on `next`. Which I force-pushed yesterday, so make sure to pull first. I always use `--with-lease` so it should be painless, but this might be the first time I've seen it put to the test.

2024-06-26 22:26 UTC, olets approved these changes

2024-06-28 14:48 UTC, henrebotha commented
Rebased onto latest `next`. Do I point the MR at `next` or `main`?

2024-06-29 06:45 UTC, olets commented
`next`. I'll merge right away

2024-07-01 14:13 UTC, henrebotha commented
Alright, rebased again one last time for old times' sake and force-pushed. MR now points at `next` and contains only a single commit.

2024-07-29 04:33 UTC, merged

2024-07-29 04:34 UTC, olets commented
Merged at long last!

2024-07-29 08:43 UTC, henrebotha commented
Despair! I am a fool. I somehow messed it up again. I'll try a follow-up PR to straighten it out.

2024-07-29 19:37 UTC, olets commented
Bet it was me, I did a lot of rebasing yesterday 😄