Respect multiline Git aliases
olets/zsh-abbr pull request #31
Opened 2020-12-02 12:24 UTC by henrebotha

It is possible to define a Git alias that contains line breaks. Previously, this would result in zsh-abbr attempting to parse each
individual line as if it were a separate alias, resulting in lots of errors. The cause of this was splitting the output of `git config --get-regexp` on line breaks.

This change splits the output of `git config --get-regexp` on newlines followed by the string "alias.", thereby ensuring that an alias that takes multiple lines gets treated as a unit.

Unfortunately this splitting doesn't get rid of the prefix "alias." on the very first alias, and so we need to retain the substitution that gets rid of this prefix.

Resolves #30.

2020-12-02 14:53 UTC, olets requested changes
Thanks for the contribution! And I appreciate having both an issue and a PR. Wonder if this can be done without calling out to an external command. Does `(s:$'\n'alias:)` or similar work? If we do go with `ps` let's do `'command' 'ps'` to protect against aliases

2020-12-02 15:25 UTC, henrebotha commented
Oh, this isn't an external command. `${(f)"$(foo)"}` is short for `${(ps|\n|)"$(foo)"}` (see "Parameter Expansion Flags" in `man zshexpn`), so I'm doing virtually the same thing here, just replacing the pattern `\n` with `\nalias.`.

2020-12-02 15:49 UTC, olets commented
Oh yes I read to hastily. Thought I was seeing `ps | …`. Great, will move forward with this later today

2020-12-13 20:00 UTC, olets approved these changes

2020-12-13 20:03 UTC, merged

2020-12-13 21:59 UTC, olets commented
Released in [v4.2.0](https://github.com/olets/zsh-abbr/releases/tag/v4.2.0)

Thanks for the contribution!